# Generated by Django 4.2 on 2023-11-11 15:18

import apps.commons.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('fio', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=100, validators=[apps.commons.validators.RegexValidatorPhone(limit_value='^(\\+7|8)[0-9]{9}')], verbose_name='Номер телефона')),
                ('request_type', models.CharField(choices=[('callback', 'Заявка на звонок'), ('call_master', 'Заявка на вызов мастера')], max_length=50, verbose_name='Тип заявки')),
            ],
            options={
                'verbose_name': 'Заявки',
                'verbose_name_plural': 'Завка на звонок',
            },
        ),
    ]
