# Generated by Django 4.2 on 2023-05-28 18:30

import apps.commons.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('fio', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=100, validators=[apps.commons.validators.RegexValidatorPhone(limit_value='^(\\+7|8)[0-9]{9}')], verbose_name='Номер телефона')),
                ('comment', models.TextField(blank=True, max_length=500, null=True, verbose_name='Комментарий менеджера')),
                ('status_comment', models.IntegerField(choices=[(1, 'Необработанная'), (2, 'В работе'), (3, 'Закрытая')], default=1, verbose_name='Статус заявки')),
            ],
            options={
                'verbose_name': 'Заявки',
                'verbose_name_plural': 'Завка на звонок',
            },
        ),
    ]
