# Generated by Django 4.2 on 2024-01-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_systemusernotifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemusernotifications',
            name='recipients',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
