# Generated by Django 4.2 on 2024-01-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_systemusernotifications_recipients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemusernotifications',
            name='channel',
            field=models.IntegerField(choices=[(1, 'Telegram'), (999, 'Amocrm')], verbose_name='Канал'),
        ),
    ]
