# Generated by Django 4.2 on 2024-01-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_systemusernotifications_channel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemusernotifications',
            options={'verbose_name': 'Систмные оповещения', 'verbose_name_plural': 'Систмное оповещение'},
        ),
        migrations.AlterField(
            model_name='systemusernotifications',
            name='template',
            field=models.TextField(verbose_name='Шаблон сообщения'),
        ),
    ]
