# Generated by Django 4.2 on 2024-01-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_systemusernotifications_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemusernotifications',
            name='recipients',
            field=models.CharField(blank=True, choices=[('managers', 'Менеджеры'), ('developers', 'Разработчики'), ('hrs', 'HR-специалисты'), ('specialists', 'Специалистам')], max_length=128, null=True),
        ),
    ]
