version: '3.3'

services:
  web:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['./entrypoint.sh']
    volumes:
      - ./src/:/usr/src/app/
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    expose:
      - 8000
    env_file:
      - src/.env.prod

  huey:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: python3 manage.py run_huey
    volumes:
      - ./src/:/usr/src/app/
    env_file:
      - src/.env.prod

  redis:
    image: redis:latest

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-without-ssl
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    ports:
      - 80:80
    restart: always
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
