# Generated by Django 4.2 on 2023-11-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовок')),
                ('answer', models.CharField(max_length=255, verbose_name='Ответ/Описание')),
                ('faq_type', models.CharField(choices=[('question', 'Секция вопросов'), ('reason', 'Секция причины')], max_length=64, verbose_name='Тип подсказки')),
            ],
        ),
    ]
