# Generated by Django 4.2 on 2023-05-28 18:30

import apps.commons.utils
import apps.commons.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('extension', models.CharField(max_length=25, null=True)),
                ('object_id', models.IntegerField(null=True)),
                ('file', models.FileField(upload_to=apps.commons.utils.set_upload_path, verbose_name='Логотип')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('extension', models.CharField(max_length=25, null=True)),
                ('object_id', models.IntegerField(null=True)),
                ('file', models.FileField(upload_to=apps.commons.utils.set_upload_path, verbose_name='Изображение')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('extension', models.CharField(max_length=25, null=True)),
                ('object_id', models.IntegerField(null=True)),
                ('file', models.FileField(upload_to=apps.commons.utils.set_upload_path, validators=[django.core.validators.FileExtensionValidator(['doc', 'docx', 'pdf']), apps.commons.validators.BaseSizeValidator(20971520)], verbose_name='Файл')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
