# Generated by Django 4.2 on 2023-05-28 18:30

import apps.contacts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('work_time', models.CharField(max_length=300, verbose_name='Время работы')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=1024, verbose_name='Ссылка')),
                ('contact', models.ForeignKey(default=apps.contacts.models.Contacts.get_default_pk, on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='contacts.contacts')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_connection', models.IntegerField(choices=[(1, 'Телефон'), (2, 'Email')], verbose_name='Тип связи')),
                ('text', models.CharField(max_length=150, verbose_name='Данные для связи')),
                ('contact', models.ForeignKey(default=apps.contacts.models.Contacts.get_default_pk, on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='contacts.contacts')),
            ],
        ),
    ]
