# Generated by Django 4.2 on 2023-11-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'Доставка', 'verbose_name_plural': 'Данные по доставке'},
        ),
        migrations.AddField(
            model_name='connection',
            name='name',
            field=models.CharField(blank=True, max_length=75, verbose_name='Название'),
        ),
    ]
