# Generated by Django 4.2 on 2023-11-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_delivery_options_connection_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='name',
        ),
        migrations.AddField(
            model_name='sociallinks',
            name='name',
            field=models.CharField(blank=True, max_length=75, verbose_name='Название'),
        ),
    ]
