# Generated by Django 4.2 on 2023-12-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_remove_connection_name_sociallinks_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describe', models.TextField(verbose_name='Описание')),
                ('youtube_id', models.CharField(blank=True, max_length=120, verbose_name='ID видео на YoTube')),
            ],
            options={
                'verbose_name': 'Раздел о нас',
                'verbose_name_plural': 'О нас',
            },
        ),
    ]
