# Generated by Django 4.2 on 2023-11-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200)),
                ('describe', models.CharField(max_length=255, null=True, verbose_name='Описание')),
                ('actual', models.BooleanField(default=True, verbose_name='Активность позиции')),
            ],
            options={
                'verbose_name': 'Тип мебели',
                'verbose_name_plural': 'Мебель',
            },
        ),
    ]
