# Generated by Django 4.2 on 2023-11-16 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='furniture',
            old_name='actual',
            new_name='is_actual',
        ),
    ]
