# Generated by Django 4.2 on 2023-12-12 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0003_furnituretypes_remove_furniture_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='furniture',
            options={'verbose_name': 'Объект', 'verbose_name_plural': 'Примеры мебели'},
        ),
        migrations.AlterModelOptions(
            name='furnituretypes',
            options={'verbose_name': 'Тип мебели', 'verbose_name_plural': 'Типы мебели'},
        ),
    ]
