# Generated by Django 4.2 on 2024-01-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0004_alter_furniture_options_alter_furnituretypes_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='describe',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
